### PR TITLE
Use requests lib

### PR DESCRIPTION
**Pull request by strarsis**
Use requests lib which simplifies/improves code and correctly handles IDNs.

Related to discussion:
https://discourse.roots.io/t/domains-with-special-characters-punycode-umlaut/11376/4

### CODE REVIEW

**Comment by strarsis** [comment]
Maybe one should just use the already punycode-escaped IDNs in wordpress_sites config?

**Comment by swalkinshaw** [comment]
I'd avoid pip and other dependencies. Did the punycode-escaping work for you? I know you had another error in your discourse thread but not sure if that was unrelated or not.

**Comment by strarsis** [comment]
I escaped the domain myself and then use it that way (escaped) in config file. This works fine.

**Comment by swalkinshaw** [comment]
I'd prefer to fix by encoding it properly if we can (something like I suggested in the thread), otherwise punycode-escaping seems correct since technically it's not a valid URI as is anyway.

**Pull request closed without merging**
