### PR TITLE
Using variable for location instead of hard-coded

### PR DESCRIPTION
**Pull request by hemangajmera**
I closed https://github.com/roots/trellis/pull/1313 by mistake, so created another one.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
https://github.com/roots/trellis/blob/7a85b293df2e7aefaee73488be42e70a008b7ed3/roles/wordpress-install/tasks/directories.yml#L4 needs to be updated as well.

Also not sure about the generic `location_path` name; it's not very descriptive. What about `public_path`? And `public_uploads_path`

**Comment by hemangajmera** [comment]
`public_path` and `public_upload_path` sounds better. Will create another request...

**Comment by hemangajmera** [comment]
Also updated the code at https://github.com/roots/trellis/blob/7a85b293df2e7aefaee73488be42e70a008b7ed3/roles/wordpress-install/tasks/directories.yml#L4

**Comment by hemangajmera** [comment]
Created clean pull request https://github.com/roots/trellis/pull/1378

**Comment by hemangajmera** [comment]
Closing it.

**Pull request closed without merging**
