### PR TITLE
PHP 7.0

### PR DESCRIPTION
**Pull request by swalkinshaw**
See https://github.com/roots/trellis/issues/431.

Todo:

- [x] Xdebug (no official package yet)
- [x] memcached

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Yes! Looking forward to testing this.

**Comment by craigpearson** [comment]
Forget Christmas and my birthday. This is the only thing I'm looking forward to in life!

**Comment by fgilio** [comment]
Super exited to try it out!

**Comment by egamipeaks** [comment]
https://github.com/roots/trellis/blob/php-7.0/roles/deploy/hooks/finalize-after.yml#L33-L36 should be restarting php7.0-fpm

**Comment by swalkinshaw** [comment]
@egamipeaks thanks. Updated that and some other old references too.

**Comment by austinpray** [comment]
Gonna spin it up in Intellij to make sure xdebug is good to go

**Comment by kalenjohnson** [comment]
Don't worry Austin, I gots it. xdebug confirmed installed and working

**Comment by austinpray** [comment]
xdebug works 
image

**Comment by mAAdhaTTah** [comment]
YES! Gonna test this weekend.

**Comment by andrewfrankel** [comment]
Tested provisioning, deployments, xdebug, etc. All looks good to me!

**Comment by swalkinshaw** [comment]
@andrewfrankel thanks for testing!

**Comment by andrewfrankel** [comment]
Ran into an issue provisioning a new server on php7 today. Got the error below, and was able to resolve by changing the PPA to  **repo: "ppa:ondrej/php"** (removed 7.0)

```
TASK: [php | Install PHP 7.0] ************************************************* 
failed: [162.243.131.66] => (item=php7.0-common,php7.0-cli,php7.0-curl,php7.0-dev,php7.0-fpm,php7.0-gd,php7.0-mcrypt,php7.0-mysql,php7.0-opcache) => {"failed": true, "item": "php7.0-common,php7.0-cli,php7.0-curl,php7.0-dev,php7.0-fpm,php7.0-gd,php7.0-mcrypt,php7.0-mysql,php7.0-opcache"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-cli : Depends: php7.0-common (>= 7.0.2-2+deb.sury.org~trusty+1) but 7.0.2-1+deb.sury.org~trusty+1 is to be installed
              Recommends: php-readline but it is not going to be installed
 php7.0-dev : Depends: php7.0-common (>= 7.0.2-2+deb.sury.org~trusty+1) but 7.0.2-1+deb.sury.org~trusty+1 is to be installed
              Recommends: dh-php7.0 but it is not installable
              Recommends: pkg-php-tools but it is not going to be installed
 php7.0-fpm : Depends: php7.0-common (>= 7.0.2-2+deb.sury.org~trusty+1) but 7.0.2-1+deb.sury.org~trusty+1 is to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" --force-yes  install 'php7.0-common' 'php7.0-cli' 'php7.0-curl' 'php7.0-dev' 'php7.0-fpm' 'php7.0-gd' 'php7.0-mcrypt' 'php7.0-mysql' 'php7.0-opcache'' failed: E: Unable to correct problems, you have held broken packages.

```

**Comment by swalkinshaw** [comment]
@andrewfrankel weird, I just tried it again fresh and it all worked. The PPA still exists: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0

The other one you used is slightly different: https://launchpad.net/~ondrej/+archive/ubuntu/php. It's for "co-installable" 7.0 and 5.6

**Comment by andrewfrankel** [comment]
@swalkinshaw, tried again today with the original PPA for dedicate 7.0 and worked fine.

I noticed that yesterday (1/14/2016) the PPA packages were updated to version 7.0.2-2 from 7.0.2-1. Wonder if it was just really bad timing with all the dependancies being updated and when I ran the provision, because those are the exact versions that were throwing conflicts for me.

Anyway, false alarm, thanks for checking!

**Comment by QWp6t** [comment]
This is working for me. :+1:

```
vagrant@example:~$ php -v
PHP 7.0.1-4+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
```

**Pull request merged**
