### PR TITLE
Add [arch=amd64] to nginx_ppa

### LINKED ISSUE #1239: Small issue with nginx mainline repo and apt update
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The current nginx mainline repo causes a warnng with `apt update`:
```
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'http://nginx.org/packages/mainline/ubuntu bionic InRelease' doesn't support architecture 'i386'
```

## Steps to reproduce

1. run `apt update`

**Expected behavior:** No warning/error message.

**Actual behavior:** Warning/error message.

**Reproduces how often:** 100%

## Versions

HEAD
OS: Linux Mint 20

## Additional information

I guess adding `[arch=amd64]` should fix this, i.e.:
`nginx_ppa: "deb [arch=amd64] http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"`
in `roles/nginx/defaults/main.yml`

### PR DESCRIPTION
**Pull request by mockey**
closes #1239

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Thanks 👍

**Comment by TangRufus** [comment]
If you receive warnings of `Target Packages (nginx/XXX) is configured multiple times` during `$ sudo apt update`, remove the old `nginx_ppa` from `/etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list` manually:


```diff
- deb http://nginx.org/packages/mainline/ubuntu bionic nginx
  deb [arch=amd64] http://nginx.org/packages/mainline/ubuntu bionic nginx
```

The warnings:

```sh-session
$ sudo apt update
...
Hit:10 http://ppa.launchpad.net/nginx/mainline/ubuntu bionic InRelease
...
W: Target Packages (nginx/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target Packages (nginx/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target Translations (nginx/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target CNF (nginx/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target CNF (nginx/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target Packages (nginx/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target Packages (nginx/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target Translations (nginx/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target CNF (nginx/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
W: Target CNF (nginx/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:1 and /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list:2
```

**Comment by mockey** [comment]
Does that mean reprovisioning adds a second line to `/etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list`?

**Comment by TangRufus** [comment]
Yes

**Comment by mockey** [comment]
That's not so good. There does not seem to be an overwrite option for `apt_repository` or something.
But reprovisioning with a changed config seems to be tricky anyway...

**Comment by swalkinshaw** [comment]
It's just a warning right? Not ideal, but not breaking anything.

**Comment by TangRufus** [comment]
> It's just a warning right? Not ideal, but not breaking anything.

Correct

**Comment by strarsis** [comment]
I get these warnings with `apt` updates:
````
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'http://nginx.org/packages/mainline/ubuntu focal InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://mariadb.mirror.globo.tech/repo/10.5/ubuntu focal InRelease' doesn't support architecture 'i386'
````
These are just warnings, but can I get rid of those?

**Comment by swalkinshaw** [comment]
And you have this PR 🤔 ? It's meant to fix that exact issue (see https://github.com/roots/trellis/issues/1239)

**Comment by strarsis** [comment]
@swalkinshaw: I was removed again with another, later PR:
https://github.com/roots/trellis/pull/1318

But

**Pull request merged**
