### PR TITLE
Fix some deprecation warnings while deploying and use current stable WP-CLI

### PR DESCRIPTION
**Pull request by mockey**
WP-CLI URL taken from: http://wp-cli.org/#install

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Re: the WP-CLI link. We had discussion about it in https://github.com/roots/trellis/issues/391 and decided to lock the version down.

**Comment by retlehs** [comment]
@mockey WP-CLI 0.23.0 came out yesterday, can you please update this PR to use that version?

then squash the commits and this is good to go :+1:

**Comment by mockey** [comment]
OK like this?

**Comment by retlehs** [comment]
thanks!

**Pull request merged**
