### PR TITLE
Support Ansible 2.9

### PR DESCRIPTION
**Pull request by swalkinshaw**

### CODE REVIEW

**Comment by TangRufus** [comment]
```sh-session
$ trellis provision production

TASK [wordpress-setup : Warn about deprecated Nginx includes directory] ********
System info:
  Ansible 2.9.6; Darwin
  Trellis version (per changelog): "Support Ansible 2.9"
---------------------------------------------------

The conditional check 'True in nginx_includes_templates.files |
map(attribute='path') | map('search', nginx_includes_deprecated |
regex_escape) | list' failed. The error was: no filter named 'search'

The error appears to be in '/xxx/roles/wordpress-
setup/tasks/nginx-includes.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Warn about deprecated Nginx includes directory
  ^ here

fatal: [111.222.333.444]: FAILED! => {}
```


```sh-session
$ trellis exec ansible --version
ansible 2.9.6
  config file = /xxx/trellis/ansible.cfg
  configured module search path = ['/yyy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /xxx/.trellis/virtualenv/lib/python3.7/site-packages/ansible
  executable location = /xxx/.trellis/virtualenv/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

See: https://github.com/roots/trellis/blob/0875cc2c637339248f69d1e93c91352952af9b54/roles/wordpress-setup/tasks/nginx-includes.yml#L16

---

Works fine on Ansible 2.8.10

```sh-session
$ trellis exec ansible --version
ansible 2.8.10
  config file = /xxx/trellis/ansible.cfg
  configured module search path = ['/yyy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /xxx/.trellis/virtualenv/lib/python3.7/site-packages/ansible
  executable location = /xxx/.trellis/virtualenv/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```
---

I couldn't find any ansible announcements related to the `search` filter.

**Comment by TangRufus** [comment]
Also add ansible 2.9 tests on CircleCI, see: https://github.com/roots/trellis/pull/1171

**Comment by swalkinshaw** [comment]
🤔 that's a tough one to fix since the suggestion won't work here.

One idea is to just remove that deprecation now? It's been 3-4 years 😅

**Comment by TangRufus** [comment]
> One idea is to just remove that deprecation now? It's been 3-4 years 😅

Agree

**Comment by swalkinshaw** [comment]
Here it is: https://github.com/roots/trellis/pull/1173

**Pull request merged**
