### PR TITLE
On development, whitelist all local IP ranges in Fail2ban & Ferm 

### PR DESCRIPTION
**Pull request by raph-topo**
Actually fix https://github.com/roots/trellis/issues/1181.
https://github.com/roots/trellis/pull/1183 did not solve this, see https://github.com/roots/trellis/issues/1181#issuecomment-633496169.

Solution explained by https://stackoverflow.com/a/39388565.

Actually,
```yaml
become: no
gather_facts: yes
```
are the defaults, but I made them explicit so future readers understand why it is in a separate play.

Would you prefer this in a separate role, similarly to `python_interpreter` just above?

### CODE REVIEW

**Comment by raph-topo** [comment]
Yikes! The IP is correct, but I end up with `ignoreip = 127.0.0.1/8 1 9 2 . 1 6 8 . 5 0 . 1` in `/etc/fail2ban/jail.local` What the hell is Ansible doing with variables?

**Comment by raph-topo** [comment]
Solved.

**Comment by swalkinshaw** [comment]
I get `10.0.2.2` 😅

**Comment by raph-topo** [comment]
Does WP in dev see you on `192.168.50.1` or `10.0.2.2`?

**Comment by raph-topo** [comment]
> this is just outputting ansible_control_node_ip via debug after its setup and running vagrant provision

Sorry, I did not understand what you mean. Here is my `debug` declaration:
```yaml
- name: Get control node IP
  hosts: web:&development
  become: no
  gather_facts: yes
  tasks:
    - name: Get control node IP
      set_fact:
        ansible_control_node_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"
      tags: [fail2ban, ferm]
    - debug:
        var: ansible_control_node_ip
```

**Comment by raph-topo** [comment]
With 
```yaml
    - debug:
        var: ansible_env
```
I get
```json
        "SSH_CLIENT": "192.168.50.1 4037 22",
        "SSH_CONNECTION": "192.168.50.1 4037 192.168.50.5 22",
```
which corresponds to reality.

**Comment by swalkinshaw** [comment]
This is mine:

```plain
        "SSH_CLIENT": "10.0.2.2 56830 22",
        "SSH_CONNECTION": "10.0.2.2 56830 10.0.2.15 22",
```

This is on macOS running Trellis/Vagrant normally (I even recently got a new laptop so it's a fresh setup).

**Comment by swalkinshaw** [comment]
```plain
tail -f /srv/www/example.com/logs/access.log
192.168.50.1 - - [28/May/2020:01:52:12 +0000] "GET / HTTP/2.0" 444 0 "-" "curl/7.64.1" "-"
```

**Comment by raph-topo** [comment]
Thanks!
Well… Maybe, after all, this is the wrong approach. I didn't find anything better on the web. Maybe Ansible is just unable to correctly understand local to local connections when Vagrant and/or Virtualbox are in the middle.

**Comment by raph-topo** [comment]
Re-thinking the problem at hand, I found the following: http://www.fail2ban.org/wiki/index.php/Whitelist.
That's by far the simplest solution: it's static.
Now, whatever the development setup, no local to local connection will ever get banned.
This also means any machine on any currently attached local network can now try to brute-force development. I do not think this opens any vulnerability. What do you think?
(If you are ok with this solution, I'll first squash)

**Comment by swalkinshaw** [comment]
Nice find 🎉 agreed this is much better. I like the re-org too 😄

**Pull request merged**
