### PR TITLE
Add xdebug.remote_autostart to simplify xdebug sessions

### PR DESCRIPTION
**Pull request by nathanielks**
This adds an additional flag to simplify using Xdebug locally. Instead of requiring a certain HTTP header or `$_REQUEST` value, setting `xdebug.remote_autostart=1` tells Xdebug to attempt a connection with a debugger regardless of their presence.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Makes sense to me 👍

**Comment by nathanielks** [comment]
@swalkinshaw Changelog added

**Comment by glopena** [comment]
Hi,

  I'm getting the trace below when running a production deployment.
  
  Why is this running into the production deployment pipeline?


TASK [sshd : Create a secure sshd_config] *********************************************************************************************************************
System info:
  Ansible 2.5.2; Darwin
  Trellis at "Add `xdebug.remote_autostart` to simplify xdebug sessions"
---------------------------------------------------
failed to validate
/root/.ansible/tmp/ansible-tmp-1525542800.36-18644436872727/source line 20:
Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-
sha2-256-etm@openssh.com,hmac-
ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-
sha2-256,hmac-ripemd160'.

fatal: [46.101.42.219]: FAILED! => {"changed": false, "checksum": "b7d35e56697beb3eef26812f86f681f3e098045c", "exit_status": 255, "stderr_lines": ["/root/.ansible/tmp/ansible-tmp-1525542800.36-18644436872727/source line 20: Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'."], "stdout": "", "stdout_lines": []}

**Comment by fullyint** [comment]
@glopena The `server.yml` playbook for provisioning is not running xdebug. The `System info:` section of the output indicates version for Ansible, OS, and Trellis. I realize it could appear that `Trellis at "Some CHANGELOG entry"` could appear to be an indication of where the error occured, but the intended message is "Trellis at version, indicated by latest entry in the [`CHANGELOG.md`](https://github.com/roots/trellis/blob/38e3b7a152719b2d7a08f094901e86e4c439e23c/CHANGELOG.md)". That is background to explain that the error you ran into is not actually related to this old merged PR.

I am able to reproduce the `Bad SSH2 mac spec` message if I run Trellis on Ubuntu 18.04, which apparently comes with OpenSSH_7.6p1 in which the `the hmac-ripemd160 MAC` is no longer supported (props to this [investigation into the error](https://github.com/dev-sec/ansible-ssh-hardening/issues/135#issuecomment-338979566)). 

Although we'll soon offer support for the recently released Ubuntu 18.04, Trellis is only intended for 16.04 at this time. This is indicated in the [README.md](https://github.com/roots/trellis/blob/38e3b7a152719b2d7a08f094901e86e4c439e23c/README.md#remote-server-setup-stagingproduction) and [docs](https://roots.io/trellis/docs/remote-server-setup/#requirements).

I'd recommend using Ubuntu 16.04 for the sake of proven Trellis compatibility. If you are using 18.04 and want to continue with it, you could avoid the `Bad SSH2 mac spec` error by overriding the [`sshd_macs_default`](https://github.com/roots/trellis/blob/38e3b7a152719b2d7a08f094901e86e4c439e23c/roles/sshd/defaults/main.yml#L46-L53) variable, omitting the two ripemd160 entries. For example, add the following to `group_vars/all/main.yml`:

```
sshd_macs_default:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256
```

Then rerun the `server.yml` playbook.

**Comment by glopena** [comment]
Thank you Phil.
That was exactly the issue.  Took me a few hours to figure it out on my own only to see I had your response awaiting to be read. Apologies for the rookie mistake. It's been a lot to take in.

Again, a huge thank you for your time and knowledge. Truly appreciated

**Pull request merged**
