### PR TITLE
Move *.sh files to bin/

### PR DESCRIPTION
**Pull request by nathanielks**

### CODE REVIEW

**Comment by swalkinshaw** [comment]
This probably needs docs changes as well

**Comment by nathanielks** [comment]
@swalkinshaw is there a separate repo for that? You're talking about roots.io, yeah?

**Comment by swalkinshaw** [comment]
https://github.com/roots/docs/tree/master/trellis

**Comment by nathanielks** [comment]
@swalkinshaw 👍

**Comment by nathanielks** [comment]
Updated docs: https://github.com/roots/docs/pull/55

**Comment by fullyint** [comment]
PR and docs look good to me

**Pull request merged**
