### PR TITLE
Ansible Lint: Fix `[208] File permissions unset or incorrect`

### PR DESCRIPTION
**Pull request by TangRufus**
- Testing required
- Only fixed some of the errors

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Are you basing these perms off a previously provisioned server?

**Comment by TangRufus** [comment]
Yes, except the unfinished file and `/tmp/wp-cli.pgp.gpg` which don't exist on my server.

**Review by swalkinshaw — APPROVED** [review]
Working well on a fresh provision 👍

**Comment by TangRufus** [comment]
Works fine on a existing server

**Pull request merged**
