### PR TITLE
Use official Nginx package

### PR DESCRIPTION
**Pull request by swalkinshaw**
Extracted from https://github.com/roots/trellis/pull/1197

Note: this will *not* re-install Nginx if you re-provision an already provisioned server since it's the same apt package name.

### CODE REVIEW

**Comment by TangRufus** [comment]
Question: What is the procedure to reinstall Nginx with the official ppa?

**Comment by swalkinshaw** [comment]
You'd have to manually uninstall via `apt-get remove nginx` *after* running these changes; then provision again to install from the new package. I don't know of a better/different way.

**Comment by strarsis** [comment]
Would a force-reinstall make sense? https://stackoverflow.com/questions/34260658/how-do-i-force-reinstall-a-package-with-ansible

**Comment by swalkinshaw** [comment]
@strarsis probably, but I'm wary of coding that by default into Trellis. Especially since it involves an uninstall + reinstall which means downtime.

**Comment by mockey** [comment]
Setting `nginx_package_state: latest` worked for me in re-provisioning.

**Comment by strarsis** [comment]
@mockey: Even better, when a specific nginx release is used that is from the official PPA, so the nginx version is locked in, without installing just the latest available one.

**Comment by swalkinshaw** [comment]
`latest` works in this specific case... but I think it could lead to unintended upgrades or breaking changes?

**Pull request merged**
