### PR TITLE
Normalize SSL providers

### PR DESCRIPTION
**Pull request by TangRufus**
# Normalize SSL providers `manual` and `self-signed`

 - Putting Nginx SSL configs in `{{ nginx_path }}/includes.d/{{ item.key }}/ssl`
 
 - Putting certificates in `{{ nginx_ssl_path }}/manual-certificates` or `{{ nginx_ssl_path }}/self-signed-certificates`

# Add `Certbot`

This is actually a failed attempt to replace `letsencrypt` with `Certbot`. I can't get [multiple-servers](https://roots.io/trellis/docs/ssl/#multiple-servers) implemented using `Certbot`. Help wanted!

See: #893

### CODE REVIEW

**Comment by TangRufus** [comment]
Besides, Certbot doesn't:

- detect new hostnames like #630
- not support of `--staging` yet

**Comment by swalkinshaw** [comment]
There's also two built-in Ansible modules which we could look into:

* http://docs.ansible.com/ansible/latest/openssl_certificate_module.html
* http://docs.ansible.com/ansible/latest/letsencrypt_module.html

**Comment by TangRufus** [comment]
The openssl_certificate_module requires ansiable 2.4. Is #895 going to be merged soon?

The letsencrypt_module requires us to change Nginx back and forth for acme challenge. Certbot handles it for us. I think Certbot simplifies everything.

**Comment by swalkinshaw** [comment]
If `openssl_certificate` actually helps/is simpler then we have no problem requiring 2.4 asap.

Our current LE implementation is a little convoluted so I'm open to any solution which simplifies it. Although I do think we have some more unique requirements with it.

**Comment by TangRufus** [comment]
`openssl_certificate` looks nice. Updated `self-signed-certificate` to use it.

Removed `Certbot` because:
 - it doesn't play well with pyOpenSSL which required for`openssl_certificate` , see: https://github.com/certbot/certbot/issues/5111
 - it can't be used with `letsencrypt` role on the same server

Rebased upon d96a58f. Actual changes here: https://github.com/roots/trellis/compare/ansible-2.4...TangRufus:ssl-providers

**Comment by swalkinshaw** [comment]
@TangRufus can this get a rebase?

**Comment by TangRufus** [comment]
Rebased. Note that I modified `server.yml` and `dev.yml` because ssl providers need to be tagged. Otherwise, `wordpress-setup` deletes their nginx config files.

**Comment by swalkinshaw** [comment]
Tested and working great 👍 

Only thing I ran into due to our current tags is if you want to enable SSL after, and *only* use a `wordpress` or `wordpress-setup` tag, Nginx will fail because `dhparams` weren't initially generated.

So if we want a common tag which would run all Nginx related tasks/roles, we might want to introduce a new one, or just apply `wordpress-setup` to `nginx` as well?

**Comment by TangRufus** [comment]
I vote for applying `wordpress-setup` to `nginx` because this also helps when adding or removing sites, i.e.: `Create Nginx available sites` & `Enable or disable Nginx sites` tasks

**Pull request closed without merging**
