### PR TITLE
Update ssl config

### PR DESCRIPTION
**Pull request by baradhili**
Noticed a bunch of issues being flagged by ssllabs so here is the fix for them...

### CODE REVIEW

**Comment by baradhili** [comment]
oh minor error.. forgot to comment out Strict Transport Security in ssl.conf

**Comment by swalkinshaw** [comment]
Hey @baradhili, thanks for bringing this up. I already have a PR up with some SSL config changes here: https://github.com/roots/trellis/pull/1127

edit: I didn't realize you had branched this off of that PR. Were these ssllabs issues from you trying our the new config? Or the existing Trellis one.

**Comment by baradhili** [comment]
sorry! for some reason I didn't notice the existing PR...

the issues were off master, not the new branch... silly season :)

**Comment by swalkinshaw** [comment]
Makes sense, thanks! I'm closing this since then since the work is being done in https://github.com/roots/trellis/pull/1127

**Pull request closed without merging**
