### PR TITLE
Allow for per-project packagist.com authentication

### PR DESCRIPTION
**Pull request by nathanielks**
This enables the use of a per-site packagist.com token in `wordpress_sites.yml`:
```
wordpress_sites:
  example.com:
    packagist_token: "{{ vault_example_com_packagist_token }}"
  foobar.com:
    packagist_token: "{{ vault_foobar_com_packagist_token }}"
```

If the token is present, it will configure that site on each deploy with the token before installing composer dependencies.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Shouldn't this use a vault var?

**Comment by nathanielks** [comment]
The idea would be:
```
wordpress_sites:
  example.com:
    packagist_token: "{{ vault_example_com_packagist_token }}"
  foobar.com:
    packagist_token: "{{ vault_foobar_com_packagist_token }}"
```

**Comment by swalkinshaw** [comment]
Oops, correct. Was just going by your example code which I assumed was from `wordpress_sites.yml` and not from `vault.yml`.

I'd just update that to expand the example.

**Comment by nathanielks** [comment]
Description updated!

**Comment by swalkinshaw** [comment]
This looks good but can we do it without the two "helper" vars. They aren't needed and we try and avoid them unless it really helps.

**Comment by swalkinshaw** [comment]
👏

**Pull request merged**
