### PR TITLE
Vagrant: Use DHCP by default

### PR DESCRIPTION
**Pull request by TangRufus**
Follow up on #892

### CODE REVIEW

**Comment by swalkinshaw** [comment]
If someone has a VM running and merges this in, do we know what the behaviour is?

**Comment by TangRufus** [comment]
It should continue working until they stop the VM.

Best case scenario:
Everything works. Normal `vagrant halt && vagrant up` / `vagrant reload` will pick up the new dynamic ip.

Not so good scenario:
They need to run `vagrant destory` if any conflict happens. 

Worst case scenario:
If are unlucky as me, having some buggy vagrant plugins and buggy custom scripts:
1. `vagrant halt` **all** other VMs
2. power off and destroy the problematic VM via VirtualBox GUI
3. `sudo rm /etc/exports`
4. remove related hosts from `/etc/hosts`
5. `vagrant up`

**Comment by swalkinshaw** [comment]
Okay thats about what I expected and I think it's fine 👍 

Of course they can always keep the static IP instead.

**Comment by swalkinshaw** [comment]
@TangRufus did you mean to close this?

**Comment by TangRufus** [comment]
No, mis-clicked. Sorry.

**Comment by swalkinshaw** [comment]
Want to add a changelog entry? Will merge after that.

**Comment by TangRufus** [comment]
done.

**Comment by TangRufus** [comment]
Sorry guys, my instruction about `vagrant destroy` is incorrect. I have a buggy script "cached" the IP and changed DHCP's behaviour on initial `vagrant up`, making it works like static IP.

If `vagrant halt && vagrant up` or `vagrant reload` don't work for you, do not destroy the VM:
1. power off the problematic VM via VirtualBox GUI
2. (maybe) sudo rm /etc/exports
3. (maybe) remove related hosts from /etc/hosts
4. vagrant up

**Pull request merged**
