### PR TITLE
wordpress_sites improvements

### PR DESCRIPTION
**Pull request by swalkinshaw**
* Add `to_env` filter
* Use `combine` + `to_env` for better .env templates
* Remove the need for `wp_env` and set automatically based on `env`
* Set `disable_wp_cron` by default

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Some doc updates should accompany this.

**Comment by henkler** [comment]
I think there may be an issue here with 'roles/deploy/templates/env.j2'.  Getting a failure on deploy.

failed: [staging.example.com] => (item={u'dest': u'.env', u'src': u'roles/deploy/templates/env.j2', u'name': u'.env config'}) => {"failed": true, "item": {"dest": ".env", "name": ".env config", "src": "roles/deploy/templates/env.j2"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'value'"}

**Comment by henkler** [comment]
Maybe this instead for env.j2?
```
{{ wordpress_env_defaults | combine(wordpress_sites[site].env, vault_wordpress_sites[site].env) | to_env }}
```

**Comment by vdrnn** [comment]
Yep, ran into the exact same issue after updating an existing installation. 
It goes through with @henkler's proposition `{{ wordpress_env_defaults | combine(wordpress_sites[site].env, vault_wordpress_sites[site].env) | to_env }}`

**Comment by fullyint** [comment]
Thank you @henkler for helping catch that this `env.j2` template in the `deploy` role must be different from the `env.j2` template in the `wordpress-install` role.

Your edit works. There is a bit of convention in the `deploy` role to prefer using the `project` dict, which is only slightly different:
```
{{ wordpress_env_defaults | combine(project.env, vault_wordpress_sites[site].env) | to_env }}
```

**Comment by fullyint** [comment]
@henkler Would you be interested in submitting a pull request for this?

**Comment by henkler** [comment]
Sure.  Let me run another deploy first and I'll get it submitted.

**Comment by henkler** [comment]
PR #530 submitted.

**Pull request merged**
