### PR TITLE
Nginx: Add ngx_brotli

### PR DESCRIPTION
**Pull request by TangRufus**
Depends on: #866 
Related: #863

### CODE REVIEW

**Comment by partounian** [comment]
I suggest removing the dynamic module from this PR but just leaving your statement that is depends on #866. Also, if we are making gzip static why not brotli?

**Comment by TangRufus** [comment]
> Also, if we are making gzip static why not brotli?

Compressing .br takes much longer than gzip. Better wait for #865 and think of a better way to do so.

**Comment by TangRufus** [comment]
Will this be consider to be merged, or should I extract it to be a galaxy role?

Thanks!

**Comment by swalkinshaw** [comment]
I wish this didn't require all the dynamic module support since Brotli is a nice improvement. So since it depends on the other, still thinking about it.

**Comment by TangRufus** [comment]
Dynamic module seems less intrusive because it doesn't require a custom Nginx package.

Another benefit is that it enable developers to use more Nginx modules if needed while keeping the official Nginx package intact. (Yes, i am talking about third party roles again...)

Let me know how the Roots team think about it. This pull request needs rebase.

**Comment by wilmardo** [comment]
Any update on this or #866 @swalkinshaw? In my humble opinion Brotli support would be an awesome addition to Trellis since it reduces load time by a bunch :)

**Comment by swalkinshaw** [comment]
Not yet sorry. Have other priorities in Trellis to finish first.

**Comment by eshimischi** [comment]
Instead of all these way better to install PageSpeed and make a right configuration..

**Comment by partounian** [comment]
Just wanted to say Cloudflare has brotli on by default.

**Comment by TangRufus** [comment]
This pull request was made some time ago.
Cloudflare now uses gzip level 8 and brotli by default.

If you are using Cloudflare, you don't need this pull request.

**Comment by eshimischi** [comment]
Have you ever heard of SDCH ? [Read here](https://mikandi.com/blog/tips-and-tricks/press-me-a-sdch-implementing-shared-dictionary-compression/)

**Comment by wilmardo** [comment]
@eshimischi SDCH has been deprecated some time ago: https://www.chromestatus.com/feature/5763176272494592

**Comment by eshimischi** [comment]
> @eshimischi SDCH has been deprecated some time ago: https://www.chromestatus.com/feature/5763176272494592

Oh, missed it. thanks, let's forget about it than

**Pull request closed without merging**
