### PR TITLE
Enable ioapic

### LINKED ISSUE #900: Performance can be improved dramatically with ioapic
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

No enabling `ioapic` by default.

**What is the expected or desired behavior?**

Enabling it by default.

### PR DESCRIPTION
**Pull request by jdevalk**
Fixes #900

### CODE REVIEW

**Comment by jdevalk** [comment]
Of course this should be tested for breakage, we've tested this on a couple machines but they're all 64 bit macs :)

**Comment by swalkinshaw** [comment]
Never heard of this setting before 🤔 

VB docs specially say:

> On any host, you should enable the I/O APIC for virtual machines that you intend to use in 64-bit mode. This is especially true for 64-bit Windows VMs. See Section 3.3.2, “"Advanced" tab”. In addition, for 64-bit Windows guests, you should make sure that the VM uses the Intel networking device, since there is no 64-bit driver support for the AMD PCNet card; see Section 6.1, “Virtual networking hardware”.

Considering we only support Ubuntu 64bit guests... seems like a good default. Would be nice for a few other people to test this as well.

**Comment by swalkinshaw** [comment]
Gave this a quick test and everything seemed fine. Would still like some other people to test. Especially on Windows. @kalenjohnson @QWp6t hint hint

**Comment by swalkinshaw** [comment]
Thanks for this PR. Replacing it with https://github.com/roots/trellis/pull/901 which adds a few more config options too.

**Pull request closed without merging**
