### PR TITLE
Replace system_cron with disable_wp_cron

### PR DESCRIPTION
**Pull request by swalkinshaw**
Update to match Bedrock's new setting.

Ref https://github.com/roots/trellis/issues/393 and https://github.com/roots/bedrock/pull/206

### CODE REVIEW

**Comment by retlehs** [comment]
shouldn't `disable_db_cron` be replaced with `disable_wp_cron`?

**Comment by swalkinshaw** [comment]
:sob: yes

**Comment by swalkinshaw** [comment]
@retlehs good now??

**Comment by retlehs** [comment]
what about not doing this for multisite?

**Pull request merged**
