### PR TITLE
Windows compatibility fix

### PR DESCRIPTION
**Pull request by bezko**
*  ANSIBLE_PATH should be '' instead of \__dir__ or the windows path will be used inside  the vagrant box
* use --force-yes to install ansible (fails without)

### CODE REVIEW

**Comment by kalenjohnson** [comment]
I'm not sure if I'm reading this correctly, but wouldn't passing in a blank string cause all references in `windows.sh` to also error? Like https://github.com/roots/trellis/blob/master/windows.sh#L26 , wouldn't that become `/vagrant//vendor` ?

Perhaps `sh.args = ANSIBLE_PATH` should become `sh.args = '.'` like how it was before, and if Trellis is installed to a subfolder, then this should be changed to the subfolders name.

That seems better actually than what I had proposed [here](https://github.com/roots/trellis/issues/262#issuecomment-119281682)

**Comment by bezko** [comment]
sh.args = '.' works too , not sure which one is less ugly /vagrant//vendor or /vagrant/./vendor

This is just a band-aid, I think windows.sh is broken , $ANSIBLE_PATH is always an absolute path  ( as defined in the Vagrantfile) so /vagrant/${ANSIBLE_PATH}/vendor doesn't make much sens

**Comment by louim** [comment]
I had a look at what could be done to fix this, while retaining the feature of finding the provisioning folder when it is nested.

Completely remove the `sh.args` parameter from the `Vagrantfile`.
Replace line https://github.com/roots/trellis/blob/master/windows.sh#L8 with:
```
ANSIBLE_PATH="$(find -name 'windows.sh' -printf '%h' -quit)"
```

This will look up the tree and find the `windows.sh` file. it will then assign the parent folder path to the `ANSIBLE_PATH` variable. The `-quit` parameter is to stop the lookup after a match has been found.

I  don't have a windows machine handy to test it at the moment, @bezko, would you be interested testing   ?

**Comment by kalenjohnson** [comment]
Wouldn't it be, um... down, the tree, from the Vagrantfile?

**Comment by louim** [comment]
Ahah yeah I think you are right! English is not my primary language :grin:

**Comment by kalenjohnson** [comment]
Haha no worries, just wanted to make sure ;)

**Comment by bezko** [comment]
@louim I'm not sure I understand the goal of this, windows.sh is looking for the location of itself relative to itself, isn't that always goint to be '.'?

Anyone I've got an error : 

$ find -name 'windows.sh' -printf '%h' -quit
find: invalid predicate `-quit'

**Comment by swalkinshaw** [comment]
Thanks @bezko. Went with https://github.com/roots/trellis/pull/269

**Pull request closed without merging**
