### PR TITLE
@simbaclaws made a mistake using square brackets instead of pipes in the vagrantfile...

### PR DESCRIPTION
**Pull request by Simbaclaws**
I made a mistake where I had used square brackets instead of pipes, potentially breaking the Vagrantfile. I'm sorry....

### CODE REVIEW

**Comment by Simbaclaws** [comment]
I did an actual test this time (after making some changes) to see whether it is working. Here are some screenshots of libvirt working:

Changed the memory

Running site

**Comment by Simbaclaws** [comment]
There seems to be a slight ttfb of 1-2 seconds, which I'm trying to fix but not really sure where it is coming from in the VM...

**Comment by swalkinshaw** [comment]
Thanks for the quick fix (+ @talss89) Also my fault for not noticing that.

The TTFB issue could be a lot of things but I'll merge this for now and if there's any Vagrant setting that improves that a follow-up fix is good.

**Comment by Simbaclaws** [comment]
I just added the latest commit to change the accelerator for the VM to KVM, this should make the virtual machine a lot faster, I'm hoping that fixes the TTFB issue. I'm testing that right now. This does mean that whoever uses libvirt needs kvm and qemu both installed on their machine.

**Pull request merged**
