### PR TITLE
Fix #731 - Use option stdout to fix theme paths

### LINKED ISSUE #731: Update WP theme paths task incorrectly checks wp_template_root var
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [ ] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

## Bug report

The options `template_root` and `theme_root` are overridden on deploy even if `template_root` is empty or set to `/themes` . As a result, it can break the activated theme (see discourse discussion below)

It seems the fix for #718 contains a bug: i think it should compare `wp_template_root.stdout` instead of `wp_template_root` in the Update WP theme paths task.

**Please describe your local environment:**

Ansible version: 2.2.0.0

OS: Windows 10

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

Remote

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Seems to be discussing the same bug: https://discourse.roots.io/t/the-theme-directory-theme1-does-not-exist/8485/12

### PR DESCRIPTION
**Pull request by swalkinshaw**
`wp_template_root` was just the registered Ansible var. The values needed to be checked against the `stdout` which is the actual output of the `wp get option` command.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
@tmdk @akovalyov sorry this was a really bad bug on my part :( would either of your be able to test this as well?

**Comment by akovalyov** [comment]
@swalkinshaw no need to be sorry, thank you for quick fix of that. I will try that in next couple of hours. Let's make that part great again :)

**Comment by tmdk** [comment]
@swalkinshaw it's working for me! thanks 👍

**Comment by akovalyov** [comment]
@swalkinshaw works for me as well. Thank you very much!

**Comment by swalkinshaw** [comment]
Thanks for confirming 😃

**Pull request merged**
