### PR TITLE
Use new `requirements.yml` format

### LINKED ISSUE #1401: Bug: `galaxy.yml` is non-standard and breaks `ansible-lint`
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Using `ansible-lint` on Trellis doesn't work.

#### What have you tried?
1. Reporting a bug to [`ansible-lint`](https://github.com/ansible/ansible-lint/issues/2228)
2. Renaming `galaxy.yml` -> `requirements.yml` and fixing syntax issues

#### What insights have you gained?
I believe the decision to rename `requirements.yml` to `galaxy.yml` was not the best move; `galaxy.yml` seems to be reserved for defining project meta data and also **collections** which Trellis is not

#### Possible solutions
Revert the rename and fix syntax

Before:

```yml
# galaxy.yml
- name: composer
  src: geerlingguy.composer
  version: 1.9.0
  # More roles
```

After:

```yml
# requirements.yml
---
roles:
  - name: composer
    src: geerlingguy.composer
    version: 1.9.0
  # More roles
```

#### Temporary workarounds
As above

### Steps To Reproduce

1. `pip3 install ansible-lint`
2. `cd path/to/trellis`
3. `ansible-lint`

### Expected Behavior

To lint the project correctly without error

### Actual Behavior

It doesn't lint and throws a Python error

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/home/lee/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 252, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 165, in main
    app = get_app(offline=options.offline)
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/app.py", line 252, in get_app
    _perform_mockings()
  File "/home/lee/.local/lib/python3.10/site-packages/ansiblelint/_mockings.py", line 77, in _perform_mockings
    namespace = yaml.get("namespace", None)
AttributeError: 'list' object has no attribute 'get'
```

### Versions

e497cfe002fa00fc33447131c0eb2570634453af

### PR DESCRIPTION
**Pull request by codepuncher**
Fixes #1401

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🤔 where is this format from? Their examples reflect what we currently have: https://galaxy.ansible.com/docs/using/installing.html

**Comment by TangRufus** [comment]
New format introduced because `requirements.yml` (our `galaxy.yml`) now supports both `roles` and `collections`.

See: https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

**Comment by codepuncher** [comment]
Yep, that's it; thanks @TangRufus.

On third thought, I think it is best to rename `galaxy.yml` to `requirements.yml`.

The reason is that `galaxy.yml` is reserved for a different purpose than the original `requirements.yml`.

See more: https://docs.galaxyproject.org/en/master/admin/config.html#configuration-files, https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample

Using `galaxy.yml` and running `ansible-lint` it will report `Incorrect type. Expected "Ansible Collection Galaxy".`.

**Comment by swalkinshaw** [comment]
👍  we just need to verify if the oldest supported version of Ansible supports this format

**Comment by codepuncher** [comment]
https://github.com/ansible/ansible/issues/73347

According to this thread, the new format was introduced in 2.10. Since that is the minimum supported version for Trellis, using the new format should be fine.

Additionally, as `galaxy.yml` is reserved for a different purpose, we should rename it too.

I'll test this to be sure 👍

**Comment by codepuncher** [comment]
Ansible 2.10.0 works using the new format.

```shell
$ trellis exec ansible --version
ansible 2.10.17
  config file = /Users/lee-work/Code/wordpress/roots/trellis/ansible.cfg
  configured module search path = ['/Users/lee-work/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lee-work/Code/wordpress/roots/trellis/.trellis/virtualenv/lib/python3.9/site-packages/ansible
  executable location = /Users/lee-work/Code/wordpress/roots/trellis/.trellis/virtualenv/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:28:31) [Clang 13.1.6 (clang-1316.0.21.2)]

$ trellis galaxy install
Starting galaxy role install process
- downloading role 'composer', owned by geerlingguy
...
# all works
```

**Comment by swalkinshaw** [comment]
Can we just update the format for now? We can decide on the name separately. Here's some reasoning why I renamed it before: https://github.com/roots/trellis/pull/1100

Having `requirements.txt` and `requirements.yml` seems quite confusing to me

**Comment by codepuncher** [comment]
How about `roles.yml` then?
I am pushing for the rename as `galaxy.yml` is reserved for different purposes than is used in Trellis.
Using `ansible-lint` on `galaxy.yml` expects a different schema, not `requirements.yml` contents.

**Comment by codepuncher** [comment]
Ah, I wasn't aware of the Galaxy server context there. Good to know.
All I can say is what `ansible-lint` is telling me:

```yml
# galaxy.yml
---
roles:
  - name: composer
    src: geerlingguy.composer
    version: 1.9.0

  - name: ntp
    src: geerlingguy.ntp
    version: 2.3.1

  - name: logrotate
    src: nickhammond.logrotate
    version: v0.0.5

  - name: swapfile
    src: oefenweb.swapfile
    version: v2.0.32

  - name: mailhog
    src: geerlingguy.mailhog
    version: 2.2.0
```
```shell
 │     schema[galaxy]Description: Additional properties are not allowed ('roles' was unexpected) Ansible [1, 1]
 │     Missing property "readme". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Missing property "authors". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Missing property "description". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Missing property "version". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Missing property "namespace". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Missing property "name". yaml-schema: Ansible Collection Galaxy (0) [2, 1]
 │     Property roles is not allowed. yaml-schema: Ansible Collection Galaxy (0) [2, 1]
```

**Review by swalkinshaw — APPROVED** [review]

**Comment by swalkinshaw** [comment]
Thanks @codepuncher 🚀

**Pull request merged**
