### PR TITLE
Add ansible playbook for windows-specific vagrant development

### PR DESCRIPTION
**Pull request by henkler**
When doing development with Sage on Windows using Trellis, we need at a bare minimum the following installed on the development Vagrant instance:

Node
Gulp (global)
Bower (global)

I've created a simple playbook and modifications to windows.sh to automatically pull these in on vagrant up.

### CODE REVIEW

**Comment by retlehs** [comment]
we recommend you run those on the host machine, not on the vagrant development box

**Comment by nonameolsson** [comment]
I did try to have that same workflow, with node/gulp/bower, on a Vagrant machine once. My experience with the performance was awful! It was really slow.

Running those stuff on the host machine will give a much faster performance. @henkler What is the reason that you want those things to be installed in the Vagrantmachine if the host is running Windows? I'm just curious :)

**Comment by henkler** [comment]
Actually, I didn't realize node/gulp/bower would actually build correctly without pulling in the entire php dev stack (composer, etc).

Tried it and it seems to be working.  Much less painful than doing it through Vagrant and mitigating symlink issues.  Thanks for pointing me in the right direction.

**Comment by nonameolsson** [comment]
@henkler great! :)

**Pull request closed without merging**
